"""A stand-in for the standard library's turtle module that draws on paper.

It understands the part of the turtle API the tutorial uses, opens no window,
and remembers everything drawn, so that:

- turtle programs can be smoke-tested on machines with no display (CI);
- chapter screenshots can be generated by script: `save("picture.png")`.

Install it in place of the real module *before* the program under test runs:

    import paperturtle
    sys.modules["turtle"] = paperturtle

It is deliberately forgiving about what it doesn't model (speed, tracer, the
turtle's shape). The real module is exercised separately, wherever a display
is available, because a fake can't tell you that the real thing works.
"""

import math
from pathlib import Path

type Colour = str | tuple[float, float, float]
type Point = tuple[float, float]


class Vec2D(tuple):
    """Enough of turtle.Vec2D: a tuple that prints like the real one."""

    def __new__(cls, x: float, y: float):
        return super().__new__(cls, (x, y))

    def __repr__(self) -> str:
        return f"({self[0]:.2f},{self[1]:.2f})"


class _Screen:
    def __init__(self) -> None:
        self.reset()

    def reset(self) -> None:
        self.width, self.height = 800, 600
        self.background: Colour = "white"
        self.mode255 = False
        self.items: list[tuple] = []
        self.turtles: list[Turtle] = []
        self.key_handlers: dict[str, object] = {}

    # --- the Screen API -----------------------------------------------------
    def setup(self, width: int = 800, height: int = 600, *_args, **_kwargs) -> None:
        self.width, self.height = int(width), int(height)

    def screensize(self, *_args, **_kwargs) -> tuple[int, int]:
        return self.width, self.height

    def window_width(self) -> int:
        return self.width

    def window_height(self) -> int:
        return self.height

    def bgcolor(self, *colour) -> Colour | None:
        if not colour:
            return self.background
        self.background = colour[0] if len(colour) == 1 else colour
        return None

    def colormode(self, mode: float | None = None) -> float | None:
        if mode is None:
            return 255 if self.mode255 else 1.0
        self.mode255 = mode == 255
        return None

    def onkey(self, function, key: str) -> None:
        self.key_handlers[key] = function

    onkeyrelease = onkey
    onkeypress = onkey

    def clear(self) -> None:
        self.items.clear()

    clearscreen = clear

    def title(self, *_args) -> None: ...
    def tracer(self, *_args) -> None: ...
    def update(self) -> None: ...
    def listen(self) -> None: ...
    def mainloop(self) -> None: ...
    def exitonclick(self) -> None: ...
    def bye(self) -> None: ...

    done = mainloop


_screen = _Screen()


def Screen() -> _Screen:
    return _screen


class Turtle:
    def __init__(self, *_args, **_kwargs) -> None:
        self.x, self.y, self.angle = 0.0, 0.0, 0.0
        self.is_down = True
        self.pen: Colour = "black"
        self.fill: Colour = "black"
        self.size = 1.0
        self.fill_points: list[Point] | None = None
        self.fill_index = 0
        _screen.turtles.append(self)

    # --- moving ---------------------------------------------------------------
    def _line_to(self, x: float, y: float) -> None:
        if self.is_down:
            _screen.items.append(
                ("line", (self.x, self.y), (x, y), self.pen, self.size)
            )
        self.x, self.y = x, y
        if self.fill_points is not None:
            self.fill_points.append((x, y))

    def forward(self, distance: float) -> None:
        radians = math.radians(self.angle)
        self._line_to(
            self.x + distance * math.cos(radians), self.y + distance * math.sin(radians)
        )

    def backward(self, distance: float) -> None:
        self.forward(-distance)

    def left(self, angle: float) -> None:
        self.angle = (self.angle + angle) % 360

    def right(self, angle: float) -> None:
        self.left(-angle)

    def goto(self, x, y: float | None = None) -> None:
        if y is None:
            x, y = x
        self._line_to(float(x), float(y))

    def home(self) -> None:
        self.goto(0, 0)
        self.angle = 0.0

    def setheading(self, angle: float) -> None:
        self.angle = angle % 360

    def circle(
        self, radius: float, extent: float = 360, steps: int | None = None
    ) -> None:
        steps = steps or max(12, int(abs(radius) * abs(extent) / 360 / 2))
        turn = extent / steps
        side = 2 * radius * math.sin(math.radians(turn) / 2)
        self.left(turn / 2)
        for _ in range(steps):
            self.forward(side)
            self.left(turn)
        self.right(turn / 2)

    fd, back, bk, lt, rt = forward, backward, backward, left, right
    setpos = setposition = goto
    seth = setheading

    # --- asking ---------------------------------------------------------------
    def position(self) -> Vec2D:
        return Vec2D(self.x, self.y)

    pos = position

    def xcor(self) -> float:
        return self.x

    def ycor(self) -> float:
        return self.y

    def heading(self) -> float:
        return self.angle

    def isdown(self) -> bool:
        return self.is_down

    def distance(self, x, y: float | None = None) -> float:
        if y is None:
            x, y = x
        return math.hypot(x - self.x, y - self.y)

    # --- the pen --------------------------------------------------------------
    def penup(self) -> None:
        self.is_down = False

    def pendown(self) -> None:
        self.is_down = True

    up, pu, down, pd = penup, penup, pendown, pendown

    def pensize(self, width: float | None = None) -> float | None:
        if width is None:
            return self.size
        self.size = width
        return None

    width = pensize

    @staticmethod
    def _colour(args: tuple) -> Colour:
        return args[0] if len(args) == 1 else args

    def pencolor(self, *args) -> Colour | None:
        if not args:
            return self.pen
        self.pen = self._colour(args)
        return None

    def fillcolor(self, *args) -> Colour | None:
        if not args:
            return self.fill
        self.fill = self._colour(args)
        return None

    def color(self, *args) -> tuple[Colour, Colour] | None:
        if not args:
            return self.pen, self.fill
        if len(args) == 2:
            self.pen, self.fill = args
        else:
            self.pen = self.fill = self._colour(args)
        return None

    def dot(self, size: float | None = None, *colour) -> None:
        size = size or max(self.size + 4, self.size * 2)
        ink = self._colour(colour) if colour else self.pen
        _screen.items.append(("dot", (self.x, self.y), size, ink))

    def begin_fill(self) -> None:
        self.fill_points = [(self.x, self.y)]
        self.fill_index = len(_screen.items)

    def end_fill(self) -> None:
        if self.fill_points and len(self.fill_points) > 2:
            shape = ("polygon", tuple(self.fill_points), self.fill)
            _screen.items.insert(self.fill_index, shape)
        self.fill_points = None

    def write(self, text: object, *_args, **_kwargs) -> None:
        _screen.items.append(("text", (self.x, self.y), str(text), self.pen))

    def clear(self) -> None:
        _screen.items.clear()

    def reset(self) -> None:
        self.clear()
        self.home()

    def speed(self, *_args) -> None: ...
    def hideturtle(self) -> None: ...
    def showturtle(self) -> None: ...
    def shape(self, *_args) -> None: ...
    def shapesize(self, *_args, **_kwargs) -> None: ...

    ht, st = hideturtle, showturtle


Pen = RawTurtle = RawPen = Turtle


def mainloop() -> None: ...
def bye() -> None: ...
def exitonclick() -> None: ...


done = mainloop


# --- for tests and screenshot scripts, not part of the turtle API -------------
def reset() -> None:
    """Forget everything drawn, ready for the next program."""
    _screen.reset()


def drawn(kind: str = "line") -> list[tuple]:
    """Everything of one kind drawn so far: "line", "dot", "polygon" or "text"."""
    return [item for item in _screen.items if item[0] == kind]


def press(key: str) -> None:
    """Pretend the user pressed a key that the program bound with onkey()."""
    _screen.key_handlers[key]()


def save(path: str | Path, scale: int = 2) -> None:
    """Render the drawing as an image. Needs Pillow, which tests do without."""
    from PIL import Image, ImageColor, ImageDraw

    # Tk uses the X11 colour names, which differ from Pillow's CSS ones here.
    x11 = {"green": (0, 255, 0), "grey": (190, 190, 190), "gray": (190, 190, 190)}
    x11 |= {"maroon": (176, 48, 96), "purple": (160, 32, 240)}

    def rgb(colour: Colour) -> tuple[int, int, int]:
        if isinstance(colour, str):
            name = colour.replace(" ", "").lower()
            return x11.get(name) or ImageColor.getrgb(name)[:3]
        top = 1 if _screen.mode255 else 255
        return tuple(int(part * top) for part in colour)

    def place(point: Point) -> Point:
        x, y = point
        return (_screen.width / 2 + x) * scale, (_screen.height / 2 - y) * scale

    size = (_screen.width * scale, _screen.height * scale)
    image = Image.new("RGB", size, rgb(_screen.background))
    paper = ImageDraw.Draw(image)
    for kind, *details in _screen.items:
        if kind == "line":
            start, end, colour, width = details
            thickness = max(1, round(width * scale))
            paper.line([place(start), place(end)], fill=rgb(colour), width=thickness)
            if thickness > 2:
                for x, y in (place(start), place(end)):
                    r = thickness / 2
                    paper.ellipse([x - r, y - r, x + r, y + r], fill=rgb(colour))
        elif kind == "dot":
            centre, diameter, colour = details
            (x, y), r = place(centre), diameter * scale / 2
            paper.ellipse([x - r, y - r, x + r, y + r], fill=rgb(colour))
        elif kind == "polygon":
            points, colour = details
            paper.polygon([place(p) for p in points], fill=rgb(colour))
        elif kind == "text":
            where, text, colour = details
            paper.text(place(where), text, fill=rgb(colour))
    image = image.resize((_screen.width, _screen.height), Image.Resampling.LANCZOS)
    image.save(path)
